- gz_topic_name: /clicked_point
  gz_type_name: ignition.msgs.Vector3d
  ros_topic_name: /clicked_point
  ros_type_name: geometry_msgs/msg/PointStamped
- gz_topic_name: /diff_drive_controller/cmd_vel
  gz_type_name: ignition.msgs.Twist
  ros_topic_name: /diff_drive_controller/cmd_vel
  ros_type_name: geometry_msgs/msg/TwistStamped
- gz_topic_name: /diff_drive_controller/odom
  gz_type_name: ignition.msgs.Odometry
  ros_topic_name: /diff_drive_controller/odom
  ros_type_name: nav_msgs/msg/Odometry
- gz_topic_name: /goal_pose
  gz_type_name: ignition.msgs.Pose
  ros_topic_name: /goal_pose
  ros_type_name: geometry_msgs/msg/PoseStamped
- gz_topic_name: /initialpose
  gz_type_name: ignition.msgs.PoseWithCovariance
  ros_topic_name: /initialpose
  ros_type_name: geometry_msgs/msg/PoseWithCovarianceStamped
- gz_topic_name: /joint_states
  gz_type_name: ignition.msgs.Model
  ros_topic_name: /joint_states
  ros_type_name: sensor_msgs/msg/JointState
- gz_topic_name: /robot_description
  gz_type_name: ignition.msgs.StringMsg
  ros_topic_name: /robot_description
  ros_type_name: std_msgs/msg/String
- gz_topic_name: /tf
  gz_type_name: ignition.msgs.Pose_V
  ros_topic_name: /tf
  ros_type_name: tf2_msgs/msg/TFMessage
- gz_topic_name: /tf_static
  gz_type_name: ignition.msgs.Pose_V
  ros_topic_name: /tf_static
  ros_type_name: tf2_msgs/msg/TFMessage
- gz_topic_name: /clock
  gz_type_name: ignition.msgs.Clock
  ros_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
- gz_topic_name: /gazebo/resource_paths
  gz_type_name: ignition.msgs.StringMsg_V
  ros_topic_name: /gazebo/resource_paths
  ros_type_name: ros_gz_interfaces/msg/StringVec
- gz_topic_name: /gui/camera/pose
  gz_type_name: ignition.msgs.Pose
  ros_topic_name: /gui/camera/pose
  ros_type_name: geometry_msgs/msg/TransformStamped
- gz_topic_name: /world/empty/clock
  gz_type_name: ignition.msgs.Clock
  ros_topic_name: /world/empty/clock
  ros_type_name: rosgraph_msgs/msg/Clock
- gz_topic_name: /world/empty/dynamic_pose/info
  gz_type_name: ignition.msgs.Pose_V
  ros_topic_name: /world/empty/dynamic_pose/info
  ros_type_name: tf2_msgs/msg/TFMessage
- gz_topic_name: /world/empty/pose/info
  gz_type_name: ignition.msgs.Pose_V
  ros_topic_name: /world/empty/pose/info
  ros_type_name: tf2_msgs/msg/TFMessage
