# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - gripper_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - arm_joint0
      - arm_joint1
      - arm_joint2
    action_ns: follow_joint_trajectory
    default: true

  gripper_group_controller:
    type: FollowJointTrajectory
    joints:
      - arm_joint3
    action_ns: follow_joint_trajectory
    default: true